import './light'
import './outlet'
import './switch'
import './camera'
import './doorbell'
import './vacuum';
import './sensor';
import './garage';
import './thermostat';
import './lock';
import './fan';
import './sprinkler';
