import './camera';
import './doorbell';
import './fan';
import './garage';
import './irrigation';
import './light';
import './lock';
import './mediaplayer';
import './security';
import './sensor';
import './switch';
import './thermostat';
import './vacuum';
import './outlet';
import './notifier';
import './windowcovering'
