import './light'
import './switch'
import './fan'
import './lock';
import './sensor';
import './camera';
import './thermostat';
import './mediaplayer';
import './vacuum';
import './doorbell';
import './irrigation';
