ARG BASE="ghcr.io/koush/scrypted-common:noble-amd"
FROM $BASE

ENV SCRYPTED_DOCKER_FLAVOR="amd"

# amd opencl
RUN curl https://raw.githubusercontent.com/koush/scrypted/main/install/docker/install-amd-graphics.sh | bash
