name: Test

on:
  push:
    branches: ["main"]
    paths: ["install/**", ".github/workflows/test.yml"]
  pull_request:
    paths: ["install/**", ".github/workflows/test.yml"]
  workflow_dispatch:
  
jobs:
  test_local:
    name: Test local installation on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-14, macos-14-large, windows-latest]
    
    steps:
      - name: Install scrypted server
        uses: scryptedapp/setup-scrypted@v0
        with:
          branch: ${{ github.sha }}