name: "Container Scan"
on:
  push:
    branches: [ "main" ]
  pull_request:
  schedule:
    - cron: '24 19 * * 3'
jobs:
  trivy-scan:
    name: Trivy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "16-bullseye"]
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Build and push Docker image (scrypted)
       uses: docker/build-push-action@v2
       with:
         build-args: BASE=${{ matrix.node }}
         context: .
         file: docker/Dockerfile
         platforms: linux/amd64,linux/arm64,linux/armhf
         push: false
         load: true
         tags: |
           koush/scrypted:${{ matrix.node }}
         cache-from: type=gha
         cache-to: type=gha,mode=max
     - name: Scan
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: koush/scrypted:${{ matrix.node }}
         format: 'sarif'
         output: 'trivy-results-${{ matrix.node }}.sarif'
     - name: Upload scan results to GitHub Security tab
       uses: github/codeql-action/upload-sarif@v2
       if: always()
       with:
        sarif_file: 'trivy-results-${{ matrix.node }}.sarif'